name: Build docs

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: '2.0.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make html docs
        run: nimble docs
      
      - name: Setup GH pages
        uses: actions/configure-pages@v5
      
      - name: Prepare docs artifact
        uses: github/upload-pages-artifact@v3
        with:
          path: htmldocs
      
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4